use FCC;


CREATE TABLE Dept (
	DEPTNO INT PRIMARY KEY,	
	DNAME VARCHAR (20) NOT NULL,
	LOC	VARCHAR (20) NOT NULL,	
	
);


CREATE TABLE Emp (
	EMPNO INT  PRIMARY KEY,
	ENAME VARCHAR (20) NOT NULL,
	JOB VARCHAR (25) NOT NULL,
	MGR INT DEFAULT NULL,
	HIREDATE VARCHAR (20) NOT NULL,
	SAL INT NOT NULL,
	COMM INT DEFAULT NULL,
	DEPTNO INT NOT NULL,
	FOREIGN KEY (DEPTNO) REFERENCES Dept (DEPTNO)
);


INSERT INTO	Dept ( DEPTNO, DNAME, LOC)	VALUES	(10,'ACCOUNTING','NEW YORK');
INSERT INTO	Dept ( DEPTNO, DNAME, LOC)	VALUES	(20,'RESEARCH','DALLAS');
INSERT INTO	Dept ( DEPTNO, DNAME, LOC)	VALUES	(30,'SALES','CHICAGO');
INSERT INTO	Dept ( DEPTNO, DNAME, LOC)	VALUES	(40,'OEPRATIONS','BOSTON');


INSERT INTO	Emp	( EMPNO, ENAME, JOB, MGR, HIREDATE, SAL,DEPTNO )		VALUES	(	7368,'SMITH','CLERK',7902,'17-DEC-80',800,20	);
INSERT INTO	Emp	( EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO ) VALUES	(	7499,'ALLEN','SALESMAN',7698,'20-FEB-81',1600,300,30	);
INSERT INTO	Emp	( EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO ) VALUES	(	7521,'WARD','SALESMAN',7698,'22-FEB-81',1250,500,30	);
INSERT INTO	Emp	( EMPNO, ENAME, JOB, MGR, HIREDATE, SAL,DEPTNO )		VALUES	(	7566,'JONES','MANAGER',7839 ,'02-APR-81',2975 ,20	);
INSERT INTO	Emp	( EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO ) VALUES	(	7654,'MARTIN','SALESMAN',7698,'28-SEP-81',1250,1400,30	);
INSERT INTO	Emp	( EMPNO, ENAME, JOB, MGR, HIREDATE, SAL,DEPTNO )		VALUES	(	7698,'BLAKE','MANAGER',7839 ,'01-MAY-81',2850,30 	);
INSERT INTO	Emp	( EMPNO, ENAME, JOB, MGR, HIREDATE, SAL,DEPTNO )		VALUES	(	7782,'CLARK','MANAGER',7839 ,'09-JUN-81',2450 ,10	);
INSERT INTO	Emp	( EMPNO, ENAME, JOB, MGR, HIREDATE, SAL,DEPTNO )		VALUES	(	7788,'SCOTT','ANALYST',7566 ,'09-DEC-82',3000 ,20	);
INSERT INTO	Emp	( EMPNO, ENAME, JOB, HIREDATE, SAL,DEPTNO )				VALUES	(	7839,'KING','PRESIDENT','17-NOV-81',5000 ,10	);
INSERT INTO	Emp	( EMPNO, ENAME, JOB, MGR, HIREDATE, SAL,DEPTNO )		VALUES	(	7844,'TURNER','SALESMAN',7698 ,'08-SEP-81',1500 ,30	);
INSERT INTO	Emp	( EMPNO, ENAME, JOB, MGR, HIREDATE, SAL,DEPTNO )		VALUES	(	7876,'ADAMS','CLERK',7788 ,'12-JAN-83',1100 ,20	);
INSERT INTO	Emp	( EMPNO, ENAME, JOB, MGR, HIREDATE, SAL,DEPTNO )		VALUES	(	7900,'JAMES','CLERK',7698 ,'03-DEC-81',950 ,30	);
INSERT INTO	Emp	( EMPNO, ENAME, JOB, MGR, HIREDATE, SAL,DEPTNO )		VALUES	(	7902,'FORD','ANALYST',7566 ,'03-DEC-81',3000 ,20	);
INSERT INTO	Emp	( EMPNO, ENAME, JOB, MGR, HIREDATE, SAL,DEPTNO )		VALUES	(	7934,'MILLER','CLERK',7782 ,'23-JAN-82',1300 ,10	);


/* 1 */
select * from	Emp	
select * from	Dept

/* 2 */
select SAL,COMM
from emp
where ENAME = 'JONES'

/* 3 */
select DISTINCT	DNAME
from Dept

/* 4 */
select * 
from Emp
where ENAME like '%LL%'

/* 5 */
select *
from Emp
where datediff(day,HIREDATE,SYSDATETIME()) < datediff(day,'08-SEP-81',SYSDATETIME())

/* 6 */
select SAL
from Emp
where JOB = 'CLERK' or JOB = 'SALESMAN' 

/* 7 */
select EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, SAL*100 'actual_sal',DEPTNO 
from Emp

/* 8 */
select *
from Emp
where COMM between 500 and 1200

/* 9 */
select *
from Emp
where COMM NOT IN (500,300)

/* 10 */
select COUNT(DEPTNO) AS 'Grand Total'
from Emp
where DEPTNO = 30

/* 11 */
select EMPNO, ENAME,CONCAT(ENAME,' is in dept ',DEPTNO) AS 'con', JOB, MGR, HIREDATE, SAL,DEPTNO 
from Emp

/* 12 */
select Emp.SAL,Dept.DEPTNO,Dept.DNAME, Dept.LOC
from Emp,Dept
where Emp.DEPTNO = Dept.DEPTNO
order by SAL DESC

/* 13 */
select Emp.ENAME,Emp.SAL, Emp.JOB, Dept.LOC
from Emp,Dept
where (Emp.COMM * 5)  = SAL

/* 14 */
select ENAME,SAL, CASE JOB when 'CLERK' then 
				 (CASE SAL when 800 then SAL+300 else SAL end)	else SAL end 'Salary + 300'
from Emp


/* 15 (Bonus) */
select SAL
from Emp,Dept
where Emp.DEPTNO = Dept.DEPTNO AND ( MGR = 7902 or LOC = 'Boston' )

